#
# https://www.sylvaindurand.org/making-jekyll-multilingual/
#
title: 
 de: ChainSquad.de GmbH
 en: ChainSquad.com GmbH
email: info@chainsquad.com
name: ChainSquad GmbH
author: Dr.-Ing. Fabian Schuh
aboutme: >
  My name is Fabian Schuh and I am the founder of ChainSquad GmbH. I have a
  Ph.D. in theoretical communications and am full-time in the blockchain-space
  since 2015.

vision: >
  This page serves as a place to gather personal thoughts, ideas about
  Blockchain-related topics. Thoughts are my own.

disclaimer: >
  Nothing in this site is an offer to sell, or the solicitation of an offer
  to buy, anything.

baseurl: ""
url: "https://articles.chainsquad.com"
github: chainsquad
markdown: kramdown

highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-feed

feed:
  posts_limit: 20
